# Generated by Django 2.0.7 on 2020-10-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201019_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='organization_uuid',
        ),
    ]
