# Generated by Django 2.0.7 on 2020-10-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_organization_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='sclass',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
